services:
  angular:
    build:
      context: .
      dockerfile: docker/angular/Dockerfile
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "1"
      NG_CLI_ANALYTICS: "false"
    volumes:
      - .:/workspace
      - angular_node_modules:/workspace/sandbox-app/node_modules
    stdin_open: true
    tty: true

volumes:
  angular_node_modules:
